version: "3.7"

volumes:
  db-data: { }

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=internal
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
